### ISSUE TITLE
Internet Explorer bug: TypeError("Invalid attempt to spread non-iterable instance")

### ISSUE THREAD

**Issue by mbkupfer** [Gmousse/dataframe-js#79] opened 2019-03-21 21:10 UTC
I'm receiving a type error when performing a `df.where` lookup (and I also see the same error for `df.show`. This is only on IE, doesn't occur on any other browser.

The error I get in my console is:
```
SCRIPT5022: Exception thrown and not caught
File: 0.chunk.js, Line: 9670, Column: 3
```
but by stepping into the debugger call stack, I was able to narrow it down to an exception being thrown at: `_nonIterableSpread [Line: 147, Col: 1], dataframe.js`

You can reproduce this error using the following minimal example:

```html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
  </head>


  <script src="https://gmousse.github.io/dataframe-js/dist/dataframe.js"></script>
  <script type="text/javascript">
    var df = new dfjs.DataFrame([
      {name: 'mark', age: '25'},
      {name: 'steve', age: '35'},
      {name: 'john', age: '35'}
    ]);
    debugger;
  </script>
</html>

```

And once in the debugger of IE, you will see there error for `df.where` and  `df.show()`. Many other methods worked fine though, although I didn't do an exhaustive check. 

Looking forward to hearing your thoughts on what could be going on.

**Comment by Gmousse** [comment] 2019-03-22 17:32
Hi @mbkupfer !

Thank you for reporting the issue.

Which IE version are you using ? 

I will try to catch the bug.

**Comment by Gmousse** [comment] 2019-03-22 17:43
I am able to reproduce it event on ie 11. 
It's probably due to a wrong babel or rollup configuration.

**Comment by Gmousse** [comment] 2019-03-22 19:05
I have identified the bug. It's due to the use of spread opertor followed by a generator. 
I will fix it asap.

**Comment by mbkupfer** [comment] 2019-03-22 19:08
> Which IE version are you using ?

I'm also on IE 11

> That's fantastic!

For what it is worth, I did some introspection of the transpiled Babel code and it appears that `Array.from(iter)` returns the valid array as per the console window, but the conditional above the return is failing.

![image](https://user-images.githubusercontent.com/6313008/54847195-0049f700-4c9b-11e9-8bdf-25b37e1ba1d2.png)

**Comment by mbkupfer** [comment] 2019-03-22 22:20
@Gmousse please check out my PR. I'm not sure if this is an optimal solution in terms of run-time efficiency, but it does fix the error in IE.

**Comment by Gmousse** [comment] 2019-03-23 12:07
@mbkupfer Thank you for your PR, I will add few optimizations (in order to make it working with the matrix module) and I will publish an hotfix soon

**Comment by Gmousse** [comment] 2019-03-23 12:51
Released in 1.4.1.

Thank you again @mbkupfer for the feedback and the PR.
See you next time :D.

**Closed by Gmousse** 2019-03-23 12:51 UTC
Labels: bug, difficulty: medium

**Comment by mbkupfer** [comment] 2019-03-23 20:31
@Gmousse  just pulled 1.4.1 and can confirm it is not crashing on IE!  :raised_hands: 

Thanks for prompt reply and turn-around on this fix. 

P.s I'm still learning javascript coding conventions and it was a joy combing through your source and figuring things out along the way. In addition, it is rather easy to find my way around. That said, it would be nice if you added some documentation for ./reusables. Some of the functions weren't so straight forward and some I still can't understand. Let me know your thoughts here...I would be happy to jump in and help out if you got too much on your plate.

**Comment by Gmousse** [comment] 2019-03-24 09:39
@mbkupfer Hi !

Thank you too for your reporting ! 

You're welcome to submit any PR in order to improve the library (for bug fixes, performance improvment, and new features)!

Don't worry about reusables.js, I plan to refact (few part of codes such as reusables.js was realized few years ago when I was less pragmatic about coding :D). I also plan add tutorials to make the contribution easier on the project.

I will be happy to see few contributors on the project, my available working time being limited on this library :D.
